### ISSUE TITLE
Using English names for links to stt.wiki

### ISSUE THREAD

**Issue by JanPeter1** [IAmPicard/StarTrekTimelinesSpreadsheet#17]
The tool (correctly) downloads the German names for all crew members (the same names that are used in the game when playing with a German set-up).
Clicking on a character name nicely opens the corresponding link to stt.wili, but that link usually fails when the name was translated by the game.
It would be nice if the English (original) character names also were available for comparison and to open the correct wiki link.

**Comment by IAmPicard** [comment]
I don't have a non-english account to test this. But FWIW, for the wiki links I'm just passing the string as-is to the wiki URL.

The application doesn't have a database by itself, all the information is coming in from DB's severs, including the crew name. I don't think their schema includes the english and localized names separately.

This could probably be fixed by adding alias URLs to the wiki with a non-localized string, such as the crew symbol.

**Comment by JanPeter1** [comment]
When switching the game to English, I get the original names in your tool and the Wiki links are working. 
So we can close this topic. Anyway the German translation is bad (only partially translated and words are not fitting in the graphical boxes), so playing in English is better...
