### ISSUE TITLE
Feature request - Voyage simulator

### ISSUE THREAD

**Issue by Darxide23** [IAmPicard/StarTrekTimelinesSpreadsheet#191]
There's already the ability to switch back to the "Recommendation" screen in Voyages and run another calculation on the current voyage, but it would be super helpful if we could select the skills to simulate. It would go a long way toward optimizing my crew and knowing who I can freeze and who I can keep active.

**Comment by paulbilnoski** [comment]
In the app version (not available in web version) the bottom of the voyage estimation calculator has a button to "Export CSV with crew Voyage ranking..." which computes voyage estimates for all skill pair combos for your crew. It takes in to account the options in the UI, particularly ignoring those on current voyage or shuttles or the freezer. Clicking the button (after a delay to run the estimation) provides two files to download, the second of which contains estimated voyage times for all skill pairs and the crew that accomplished it. The output ignores traits that could boost antimatter since it is not for an actual voyage, but is good for rough estimates.

**Comment by Darxide23** [comment]
This is sufficient. I've always ignored the button. Didn't know what it did.
