### ISSUE TITLE
filtering for the crew page

### ISSUE THREAD

**Issue by dharkus** [IAmPicard/StarTrekTimelinesSpreadsheet#29]
atm it shows all your crew, which can be sorted by various things, however all the crew in cryostasis are there for a reason, so it'd be good to be able to only show crew not in cryostasis, or the opposite. also only crew with a particular skills or perhaps combinations of skills (could be integrated into the search system by being able to search for skills to bring up all eng med crew for example)

**Comment by IAmPicard** [comment]
There is a "show buyback" option in the Settings menu of the crew list now (it's on by default, you can uncheck it to hide buyback crew).

Regarding cryo: you can sort by the "snowflake" / frozen column.

There's also an option to group by rarity in the Settings menu.

**Comment by stargazer001** [comment]
I'm not quite sure what you mean as the 'settings' dropdown just shows one 'thing' in the dropdown > 'Experimental - Show Stats for all Crew' 

just noticed this answer "This is fixed in the repo, as the change number suggests. If you build from source, it's there now. Otherwise it **will be available in the next release (0.8.1).** but since no answer back when it was closed had no idea.

I'm referring to the older way which also includes a breakdown / collapsible menu that also showed the 'total amount' of each rarity [as I showed also with older screenshots. ](https://github.com/IAmPicard/StarTrekTimelinesSpreadsheet/issues/159)

**Comment by IAmPicard** [comment]
You can try the [online tool](https://iampicard.com), which has the latest changes. I'll publish a new desktop version when I get a chance:

![image](https://user-images.githubusercontent.com/31076775/46987494-432eef80-d0a9-11e8-8c72-69041f22e450.png)
