### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by sfi72** [IAmPicard/StarTrekTimelinesSpreadsheet#33]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Tool version: **0.6.8**
Operating system: **win32 x64 (10.0.16299)**

Hey there! This is a suggestion/request, I'd really like to be able to see my progress towards collections on the tool.  And maybe an option to see all the characters that I don't have greyed out/without checkmarks next to them on the crew page.  I've tried using excel pages but having everything in the tool together would be a lot easier.  I'm really enjoying the tool though, I've been trying to find something like this for weeks.  Thanks!  (also I know they add new crew regularly, so maybe a button to 'add custom crew' to future proof the app.)

**Comment by IAmPicard** [comment]
About future - proofing. This is about as future proof as it gets; there is no data hard-coded in the application, everything comes in from DB's server (including the list of all crew, of course).

For showing un-owned crew, I can add that in but note that it won't have the stats (because there's no way to get stats for unowned crew from the game API).

If you're only looking for an Excel type of sheet with owned and unowned crew, I also have [the Google Sheets Add-On](https://chrome.google.com/webstore/detail/star-trek-timelines-crew/fhbgadamglhhcelbmidkmkoepekgkocl?utm_source=permalink) which already does that.

**Comment by IAmPicard** [comment]
Cryo collections have been added into the tool:
![image](https://user-images.githubusercontent.com/31076775/49325239-dc985080-f4f3-11e8-9770-20091434d1fc.png)
