### ISSUE TITLE
Gauntlet Screen - Blank

### ISSUE THREAD

**Issue by Joker41NAM** [IAmPicard/StarTrekTimelinesSpreadsheet#55]
When clicking the Gauntlet screen, it appears to pull the data (red bar at top), but after a moment goes to a completely blank window

**To Reproduce**
Click Gauntlet
Screen goes blank after a moment

**Screenshots**

![clipboard01](https://user-images.githubusercontent.com/39820552/40823632-a8199b22-6536-11e8-870a-d345cd4ae0f8.png)

**Comment by IAmPicard** [comment]
That's caused by a Js error. Can you try opening the devtools and copying the error message logged in the console there, to help with debugging?

Open the devtools by clicking on your captain name in upper-left, then on the bug icon here:
![image](https://user-images.githubusercontent.com/31076775/40578827-10235bf6-60d0-11e8-9d04-51c0ab26e5aa.png)

With the console open, navigate to the gauntlet tab to reproduce the error; it should pop up in red in the console.

**Comment by Joker41NAM** [comment]
Is this what you need?

![image](https://user-images.githubusercontent.com/39820552/40824163-c08573a0-6538-11e8-8d20-8f6adc427cde.png)

**Comment by IAmPicard** [comment]
I really need to publish a debug build, the minified names aren't readable at all.

If you click to the right of the error on the "bundle.js:134" string, can you send me a screenshot of what that looks like?

I'm attempting to map these minified names back to the source code to track down where the error occurs.

BTW, are you a coder? If you set up a node environment and build the app locally, debugging would be much easier.

**Comment by Joker41NAM** [comment]
If I understood that correctly, here's what I think you requested:

![image](https://user-images.githubusercontent.com/39820552/40825386-fe6cc44e-653c-11e8-9e96-344a53883259.png)
(there's a bit more past the end of the screen, but it looks like the same data as the .134 ones)

**Comment by IAmPicard** [comment]
If you click on the "bundle.js:134" link here:
![image](https://user-images.githubusercontent.com/31076775/40826083-69d6f236-652e-11e8-840d-631119df420b.png)

It will open a new pane with mumbled code, but importantly a column number (in the hundreds of thousands).

**Comment by Joker41NAM** [comment]
Ah, gotcha.  Here (let me know if you need resized)

![image](https://user-images.githubusercontent.com/39820552/40826154-75741efa-653f-11e8-8c40-3c1009dcb3da.png)

**Comment by Joker41NAM** [comment]
Don't know if you did anything, but it's now working again.

**Comment by IAmPicard** [comment]
I didn't push any new updates. Thank you for the help, but I wasn't able to track down the issue from the mangled code 😞 . I suspect the gauntlet was in a weird state that simply resolved itself because you ended it / started a new one.

Either way, I'm looking into better support for debugging, to hopefully be able to diagnose these sort of issues when they happen again.

**Comment by Joker41NAM** [comment]
Well, FYI for any future debugging, the issue first occurred on the 2nd match of the Gauntlet that just finished, and it was working again when I tried it with a half hour to go on the same Gauntlet.
